name: CI
on:
  push:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install flake8
      - name: Lint (fast; no heavy deps)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true
